import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Send, 
  Settings, 
  Home, 
  TrendingUp, 
  GraduationCap, 
  Globe, 
  Volume2, 
  Menu,
  X,
  Sun,
  Moon,
  Mic,
  User,
  History,
  Brain,
  ChevronDown,
  ChevronUp,
  Copy,
  Download,
  Share2,
  MessageSquare,
  BookOpen,
  BarChart2,
  HelpCircle
} from 'lucide-react';
import AIService from './services/aiService';
import './App.css';
import './mobile.css';

// Mode configurations
const modes = {
  beginner: {
    name: 'Beginner',
    icon: '🌱',
    description: 'Get simple, easy-to-understand explanations perfect for beginners.',
    theme: 'beginner',
    color: '#4CAF50',
    accent: '#2E7D32'
  },
  thinker: {
    name: 'Thinker',
    icon: '💭',
    description: 'Dive deeper into concepts with detailed analysis and reasoning.',
    theme: 'thinker',
    color: '#2196F3',
    accent: '#0D47A1'
  },
  story: {
    name: 'Story',
    icon: '📖',
    description: 'Learn through engaging stories and real-world examples.',
    theme: 'story',
    color: '#9C27B0',
    accent: '#6A1B9A'
  },
  mastery: {
    name: 'Mastery',
    icon: '🎯',
    description: 'Advanced insights and expert-level knowledge for mastery.',
    theme: 'mastery',
    color: '#FF9800',
    accent: '#E65100'
  }
};

const App = () => {
  // UI State
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [activeMode, setActiveMode] = useState(null);
  const [inputText, setInputText] = useState('');
  const [messages, setMessages] = useState({});
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [expandedModes, setExpandedModes] = useState({});
  
  // Refs
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  // Toggle dark mode
  useEffect(() => {
    if (isDarkMode) {
      document.documentElement.setAttribute('data-theme', 'dark');
    } else {
      document.documentElement.removeAttribute('data-theme');
    }
  }, [isDarkMode]);

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Toggle mode expansion
  const toggleModeExpansion = (modeKey) => {
    setExpandedModes(prev => ({
      ...prev,
      [modeKey]: !prev[modeKey]
    }));
  };

  // Handle sending a message
  const handleSendMessage = async (modeKey) => {
    if (!inputText.trim()) return;
    
    const userMessage = {
      id: Date.now(),
      text: inputText,
      sender: 'user',
      timestamp: new Date()
    };

    // Add user message to chat
    setMessages(prev => ({
      ...prev,
      [modeKey]: [...(prev[modeKey] || []), userMessage]
    }));

    setInputText('');
    setIsLoading(true);

    try {
      // Simulate AI response (replace with actual API call)
      setTimeout(() => {
        const aiResponse = {
          id: Date.now() + 1,
          text: `This is a simulated response from ${modes[modeKey].name} mode. In a real implementation, this would be generated by the AI.`,
          sender: 'ai',
          timestamp: new Date()
        };
        
        setMessages(prev => ({
          ...prev,
          [modeKey]: [...(prev[modeKey] || []), aiResponse]
        }));
        
        setIsLoading(false);
      }, 1500);
      
      // In a real app, you would call your AI service here:
      // const response = await AIService.getResponse(inputText, modeKey);
      // Then update messages with the response
      
    } catch (error) {
      console.error('Error getting AI response:', error);
      setIsLoading(false);
    }
  };

  // Toggle speech for a message
  const toggleSpeech = (text) => {
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
    } else if ('speechSynthesis' in window) {
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.onend = () => setIsSpeaking(false);
      window.speechSynthesis.speak(utterance);
      setIsSpeaking(true);
    }
  };

  // Render a single message
  const renderMessage = (message) => (
    <motion.div 
      key={message.id}
      className={`message ${message.sender}`}
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
    >
      <div className="message-content">
        <p>{message.text}</p>
      </div>
      <div className="message-actions">
        <button 
          className="action-button" 
          onClick={() => toggleSpeech(message.text)}
          aria-label={isSpeaking ? 'Stop speaking' : 'Read aloud'}
        >
          <Volume2 size={16} />
        </button>
        <button 
          className="action-button"
          onClick={() => {
            navigator.clipboard.writeText(message.text);
            // Show a toast notification in a real app
            alert('Copied to clipboard!');
          }}
          aria-label="Copy to clipboard"
        >
          <Copy size={16} />
        </button>
      </div>
    </motion.div>
  );

  // Render a mode card
  const renderModeCard = (modeKey) => {
    const mode = modes[modeKey];
    const isExpanded = expandedModes[modeKey];
    const modeMessages = messages[modeKey] || [];

    return (
      <div key={modeKey} className="capsule mode-card">
        <div 
          className="mode-header"
          onClick={() => toggleModeExpansion(modeKey)}
        >
          <div className="mode-header-content">
            <span className="mode-icon">{mode.icon}</span>
            <h3 className="mode-title">{mode.name}</h3>
            <span 
              className="mode-tag"
              style={{ 
                background: `${mode.color}20`,
                color: mode.color,
                border: `1px solid ${mode.color}40`
              }}
            >
              {mode.theme.toUpperCase()}
            </span>
          </div>
          <button 
            className="expand-button"
            aria-label={isExpanded ? 'Collapse' : 'Expand'}
          >
            {isExpanded ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
          </button>
        </div>
        
        <AnimatePresence>
          {isExpanded && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              transition={{ duration: 0.3 }}
              className="mode-content"
            >
              <p className="mode-description">{mode.description}</p>
              
              <div className="chat-container">
                {modeMessages.length > 0 ? (
                  <div className="messages">
                    {modeMessages.map(renderMessage)}
                    <div ref={messagesEndRef} />
                  </div>
                ) : (
                  <div className="empty-state">
                    <MessageSquare size={48} className="empty-icon" />
                    <p>Start a conversation with {mode.name} mode</p>
                  </div>
                )}
                
                <div className="chat-input-container">
                  <input
                    type="text"
                    value={inputText}
                    onChange={(e) => setInputText(e.target.value)}
                    placeholder={`Message ${mode.name}...`}
                    className="chat-input"
                    onKeyPress={(e) => e.key === 'Enter' && handleSendMessage(modeKey)}
                    ref={inputRef}
                  />
                  <button 
                    className="send-button"
                    onClick={() => handleSendMessage(modeKey)}
                    disabled={!inputText.trim() || isLoading}
                    aria-label="Send message"
                  >
                    <Send size={20} />
                  </button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    );
  };

  return (
    <div className="app-container">
      {/* Header */}
      <header className="header">
        <button 
          className="action-button" 
          onClick={() => setIsMenuOpen(!isMenuOpen)}
          aria-label="Toggle menu"
        >
          <Menu size={24} />
        </button>
        
        <h1 className="header-title">MiniMind</h1>
        
        <button 
          className="action-button"
          onClick={() => setIsDarkMode(!isDarkMode)}
          aria-label={isDarkMode ? 'Switch to light mode' : 'Switch to dark mode'}
        >
          {isDarkMode ? <Sun size={24} /> : <Moon size={24} />}
        </button>
      </header>
      
      {/* Main Content */}
      <main className="main-content">
        {Object.keys(modes).map(renderModeCard)}
      </main>
      
      {/* Mobile Menu */}
      <AnimatePresence>
        {isMenuOpen && (
          <>
            <div 
              className="menu-overlay"
              onClick={() => setIsMenuOpen(false)}
            />
            <motion.div 
              className="mobile-menu"
              initial={{ x: '-100%' }}
              animate={{ x: 0 }}
              exit={{ x: '-100%' }}
              transition={{ type: 'tween' }}
            >
              <div className="menu-header">
                <h2>Menu</h2>
                <button 
                  className="close-menu"
                  onClick={() => setIsMenuOpen(false)}
                  aria-label="Close menu"
                >
                  <X size={24} />
                </button>
              </div>
              
              <nav className="menu-nav">
                <button className="nav-item">
                  <Home size={20} />
                  <span>Home</span>
                </button>
                <button className="nav-item">
                  <History size={20} />
                  <span>History</span>
                </button>
                <button className="nav-item">
                  <BookOpen size={20} />
                  <span>Learn</span>
                </button>
                <button className="nav-item">
                  <BarChart2 size={20} />
                  <span>Progress</span>
                </button>
                <button className="nav-item">
                  <HelpCircle size={20} />
                  <span>Help</span>
                </button>
                <button className="nav-item">
                  <Settings size={20} />
                  <span>Settings</span>
                </button>
              </nav>
              
              <div className="menu-footer">
                <p>MiniMind v2.3.0</p>
                <p>© {new Date().getFullYear()} MiniMind</p>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
};

export default App;
